### ISSUE TITLE
Slow down! 

### ISSUE THREAD

**Issue by prakhar1989** [bahuljain/Leet-Code#1]
Solving leetcode problems in full form! :grinning: Nice! :+1: 

For some extra fun, you can create a readme file and copy/paste the following line in it.

```
![Progress](https://img.shields.io/badge/progress-50%20%2F%20285-ff69b4.svg)
```

Change the number 50 to the number of problems you have done.

This is how it'll look - 
![Progress](https://img.shields.io/badge/progress-50%20%2F%20285-ff69b4.svg)

Cool, right? :dancers:

**Comment by bahuljain** [comment]
Haha, DONE!! Thanks!!
